export const ROUTES = {
  home: "/",
  howItWorks: "/how-it-works",
  about: "/about",

  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",

  student: {
    dashboard: "/student/dashboard",
    profile: "/student/profile",
    profileEdit: "/student/profile/edit",
    transcript: "/student/profile/transcript",
    ai: "/student/ai",
    aiResults: "/student/ai/results",
    roadmap: "/student/roadmap",
    universitySearch: "/student/universities",
    savedUniversities: "/student/universities/saved",
    teachers: "/student/providers/teachers",
    teacher: (teacherId: string) => `/student/providers/teachers/${teacherId}`,
    consultants: "/student/providers/consultants",
    consultant: (id: string) => `/student/providers/consultants/${id}`,
    bookings: "/student/bookings",
    booking: (id: string) => `/student/bookings/${id}`,
    // messages: (bookingId: string) => `/student/messages/${bookingId}`,
    // review: (bookingId: string) => `/student/reviews/${bookingId}`,
  },

  provider: {
    dashboard: "/provider/dashboard",
    profile: "/provider/profile",
    verification: "/provider/verification",
    packages: "/provider/packages",
    newPackage: "/provider/packages/new",
    editPackage: (id: string) => `/provider/packages/${id}/edit`,
    bookings: "/provider/bookings",
    booking: (id: string) => `/provider/bookings/${id}`,
    // messages: (bookingId: string) => `/provider/messages/${bookingId}`,
    // reviews: "/provider/reviews",
  },

  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    providers: "/admin/providers",
    providerVerification: "/admin/providers/verification",
    provider: (id: string) => `/admin/providers/${id}`,
    successRecords: "/admin/success-records",
    bookings: "/admin/bookings",
    disputes: "/admin/disputes",
    knowledgeBase: "/admin/knowledge-base",
    universities: "/admin/knowledge-base/universities",
    programs: "/admin/knowledge-base/programs",
    scholarships: "/admin/knowledge-base/scholarships",
    moderation: "/admin/moderation",
  },
} as const;
